# -*- coding: utf-8 -*-
"""Datacleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYllG9H3VA5Psrz7BdeC6G0PmI7TWwBc
"""

import pandas as pd

# Load uploaded raw dataset
df = pd.read_csv("/mall_customers_rawdata.csv")

# Show initial shape
print(df.shape)
print(df.isnull().sum())

# Remove duplicates
df.drop_duplicates(inplace=True)

# Standardize Gender column
df['Gender'] = df['Gender'].astype(str).str.lower().str.strip()
df['Gender'] = df['Gender'].replace({
    'f': 'female',
    'fem': 'female',
    'm': 'male',
    '': pd.NA,
    'nan': pd.NA
})

# Rename columns
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Convert data types
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['annual_income'] = pd.to_numeric(df['annual_income'], errors='coerce')
df['spending_score'] = pd.to_numeric(df['spending_score'], errors='coerce')

# Drop rows with missing values
df.dropna(inplace=True)

# Save cleaned dataset
df.to_csv("cleaned_mall_customers.csv", index=False)
print("\n✅ Cleaned dataset saved.")

df_cleaned = pd.read_csv("cleaned_mall_customers.csv")
df_cleaned.head()

from google.colab import files
files.download("cleaned_mall_customers.csv")